name       : haskell-enclosed-exceptions
version    : 1.0.3
release    : 1
source     :
    - https://hackage.haskell.org/package/enclosed-exceptions-1.0.3/enclosed-exceptions-1.0.3.tar.gz : af6d93f113ac92b89a32af1fed52f445f492afcc0be93980cbadc5698f94f0b9
license    : MIT
component  : programming.haskell
summary    : Catching all exceptions from within an enclosed computation
description: |
    Catching all exceptions from within an enclosed computation
builddeps  :
    - haskell-async-devel
    - haskell-cabal-install
    - haskell-lifted-base-devel
rundeps    :
    - devel:
        - haskell-async-devel
        - haskell-lifted-base-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
